version: '3.7'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
    ulimits:
      nofile: 65536
    restart: unless-stopped

volumes:
  nexus_data:
