version: '3.7'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    restart: unless-stopped

volumes:
  vault_data:
###export VAULT_ADDR=http://localhost:8200
###export VAULT_TOKEN=myroot
###vault status
